nebstudio/lvscare:
  - source: staging/src/github.com/nebstudio/lvscare/
    dest: .
    deleteOrphaned: true

nebstudio/image-cri-shim:
  - source: staging/src/github.com/nebstudio/image-cri-shim/
    dest: .
    deleteOrphaned: true
